### ISSUE TITLE
Global hook

### ISSUE THREAD

**Issue by EnzoMartin** [davej/john#3]
Was idly thinking about this earlier, and only did some basic research on it so far, but it could be kinda neat if there's a way to create a global hook with `npm` so that it runs `john` after every post `npm install` on a directory so you don't have to add it to every `package.json` in your projects

Food for thought, gonna look at it more this weekend

**Comment by davej** [comment]
Yup, looked into this before, it's not possible to do after installing a new module in your project (i.e. `npm install some-module --save`) but you can do after doing a general `npm install`.

It's as simple as:

```js
// in package.json
  "scripts": {
    "postinstall": "john"
  },
  "devDependencies": {
    "john": "^1"
  },
```

You obviously don't need to have `john` installed globally for this to work either. Might be good to document it in the README for sure.

**Comment by davej** [comment]
Oh wait, I think I misunderstood what you've said. Yeah would be very interested in a global hook!

**Comment by EnzoMartin** [comment]
Yea, the point is for you not to have it in individual repositories, so you can have it purely installed locally in your global modules, and trigger it automatically wherever `npm install` just finished running.

I'll look at it over the weekend and see if there's a way to do it

**Comment by davej** [comment]
Cool, yeah that would be very useful!
